package com.yangz.mymusicweb.dao;

import com.yangz.mymusicweb.entity.ListSong;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ListSongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    int insert(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    int insertSelective(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    ListSong selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ListSong record);

    List<ListSong> allListSong();

    List<ListSong> listSongOfSongId(Integer songListId);

    int deleteListSong(Integer parseInt);

    int addListSong(ListSong listsong);

    int updateListSongMsg(ListSong listsong);
}