package com.yangz.mymusicweb.dao;

import com.yangz.mymusicweb.entity.Singer;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface SingerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbggenerated
     */
    int insert(Singer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbggenerated
     */
    int insertSelective(Singer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbggenerated
     */
    Singer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Singer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Singer record);

    List<Singer> allSinger();

    List<Singer> singerOfName(String name);

    List<Singer> singerOfSex(Integer parseInt);

    int deleteSinger(Integer parseInt);

    int updateSingerMsg(Singer singer);

    int updateSingerPic(Singer singer);
}